# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.8)
   message(FATAL_ERROR "CMake >= 2.8.0 required")
endif()
if(CMAKE_VERSION VERSION_LESS "2.8.3")
   message(FATAL_ERROR "CMake >= 2.8.3 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.8.3...3.27)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_cmake_targets_defined "")
set(_cmake_targets_not_defined "")
set(_cmake_expected_targets "")
foreach(_cmake_expected_target IN ITEMS Realm::Storage Realm::QueryParser Realm::ObjectStore Realm::RealmFFI Realm::RealmFFIStatic Realm::Sync)
  list(APPEND _cmake_expected_targets "${_cmake_expected_target}")
  if(TARGET "${_cmake_expected_target}")
    list(APPEND _cmake_targets_defined "${_cmake_expected_target}")
  else()
    list(APPEND _cmake_targets_not_defined "${_cmake_expected_target}")
  endif()
endforeach()
unset(_cmake_expected_target)
if(_cmake_targets_defined STREQUAL _cmake_expected_targets)
  unset(_cmake_targets_defined)
  unset(_cmake_targets_not_defined)
  unset(_cmake_expected_targets)
  unset(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT _cmake_targets_defined STREQUAL "")
  string(REPLACE ";" ", " _cmake_targets_defined_text "${_cmake_targets_defined}")
  string(REPLACE ";" ", " _cmake_targets_not_defined_text "${_cmake_targets_not_defined}")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_cmake_targets_defined_text}\nTargets not yet defined: ${_cmake_targets_not_defined_text}\n")
endif()
unset(_cmake_targets_defined)
unset(_cmake_targets_not_defined)
unset(_cmake_expected_targets)


# Create imported target Realm::Storage
add_library(Realm::Storage STATIC IMPORTED)

set_target_properties(Realm::Storage PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "\$<\$<CONFIG:Debug>:REALM_DEBUG=1>"
  INTERFACE_INCLUDE_DIRECTORIES "C:/workspace/osp-gojimmypi/realm/realm-core-gojimmypi/src;C:/workspace/osp-gojimmypi/realm/VS2022/src"
  INTERFACE_LINK_LIBRARIES "Version.lib;psapi.lib;Threads::Threads;ZLIB::ZLIB"
)

# Create imported target Realm::QueryParser
add_library(Realm::QueryParser STATIC IMPORTED)

set_target_properties(Realm::QueryParser PROPERTIES
  INTERFACE_LINK_LIBRARIES "Realm::Storage"
)

# Create imported target Realm::ObjectStore
add_library(Realm::ObjectStore STATIC IMPORTED)

set_target_properties(Realm::ObjectStore PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "\$<\$<CONFIG:Release>:NDEBUG>;\$<\$<CONFIG:RelWithDebInfo>:NDEBUG>;REALM_ENABLE_SYNC=1"
  INTERFACE_LINK_LIBRARIES "Realm::Storage;Realm::QueryParser;Realm::Sync"
)

# Create imported target Realm::RealmFFI
add_library(Realm::RealmFFI SHARED IMPORTED)

set_target_properties(Realm::RealmFFI PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "C:/workspace/osp-gojimmypi/realm/realm-core-gojimmypi/src"
)

# Create imported target Realm::RealmFFIStatic
add_library(Realm::RealmFFIStatic STATIC IMPORTED)

set_target_properties(Realm::RealmFFIStatic PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "RLM_NO_DLLIMPORT"
  INTERFACE_INCLUDE_DIRECTORIES "C:/workspace/osp-gojimmypi/realm/realm-core-gojimmypi/src"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:Realm::Storage>;\$<LINK_ONLY:Realm::ObjectStore>;\$<LINK_ONLY:Realm::QueryParser>;/workspace/wolfssl/DLL Debug/x64/wolfssl.lib;\$<LINK_ONLY:Realm::Sync>"
)

# Create imported target Realm::Sync
add_library(Realm::Sync STATIC IMPORTED)

set_target_properties(Realm::Sync PROPERTIES
  INTERFACE_LINK_LIBRARIES "Realm::Storage;/workspace/wolfssl/DLL Debug/x64/wolfssl.lib;Version.lib"
)

# Import target "Realm::Storage" for configuration "Debug"
set_property(TARGET Realm::Storage APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(Realm::Storage PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "C;CXX"
  IMPORTED_LOCATION_DEBUG "C:/workspace/osp-gojimmypi/realm/VS2022/src/realm/Debug/realm-dbg.lib"
  )

# Import target "Realm::QueryParser" for configuration "Debug"
set_property(TARGET Realm::QueryParser APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(Realm::QueryParser PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LOCATION_DEBUG "C:/workspace/osp-gojimmypi/realm/VS2022/src/realm/parser/Debug/realm-parser-dbg.lib"
  )

# Import target "Realm::ObjectStore" for configuration "Debug"
set_property(TARGET Realm::ObjectStore APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(Realm::ObjectStore PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LOCATION_DEBUG "C:/workspace/osp-gojimmypi/realm/VS2022/src/realm/object-store/Debug/realm-object-store-dbg.lib"
  )

# Import target "Realm::RealmFFI" for configuration "Debug"
set_property(TARGET Realm::RealmFFI APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(Realm::RealmFFI PROPERTIES
  IMPORTED_IMPLIB_DEBUG "C:/workspace/osp-gojimmypi/realm/VS2022/src/realm/object-store/c_api/Debug/realm-ffi-dbg.lib"
  IMPORTED_LOCATION_DEBUG "C:/workspace/osp-gojimmypi/realm/VS2022/src/realm/object-store/c_api/Debug/realm-ffi-dbg.dll"
  )

# Import target "Realm::RealmFFIStatic" for configuration "Debug"
set_property(TARGET Realm::RealmFFIStatic APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(Realm::RealmFFIStatic PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LOCATION_DEBUG "C:/workspace/osp-gojimmypi/realm/VS2022/src/realm/object-store/c_api/Debug/realm-ffi-static-dbg.lib"
  )

# Import target "Realm::Sync" for configuration "Debug"
set_property(TARGET Realm::Sync APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(Realm::Sync PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LOCATION_DEBUG "C:/workspace/osp-gojimmypi/realm/VS2022/src/realm/sync/Debug/realm-sync-dbg.lib"
  )

# Import target "Realm::Storage" for configuration "Release"
set_property(TARGET Realm::Storage APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(Realm::Storage PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "C;CXX"
  IMPORTED_LOCATION_RELEASE "C:/workspace/osp-gojimmypi/realm/VS2022/src/realm/Release/realm.lib"
  )

# Import target "Realm::QueryParser" for configuration "Release"
set_property(TARGET Realm::QueryParser APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(Realm::QueryParser PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "C:/workspace/osp-gojimmypi/realm/VS2022/src/realm/parser/Release/realm-parser.lib"
  )

# Import target "Realm::ObjectStore" for configuration "Release"
set_property(TARGET Realm::ObjectStore APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(Realm::ObjectStore PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "C:/workspace/osp-gojimmypi/realm/VS2022/src/realm/object-store/Release/realm-object-store.lib"
  )

# Import target "Realm::RealmFFI" for configuration "Release"
set_property(TARGET Realm::RealmFFI APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(Realm::RealmFFI PROPERTIES
  IMPORTED_IMPLIB_RELEASE "C:/workspace/osp-gojimmypi/realm/VS2022/src/realm/object-store/c_api/Release/realm-ffi.lib"
  IMPORTED_LOCATION_RELEASE "C:/workspace/osp-gojimmypi/realm/VS2022/src/realm/object-store/c_api/Release/realm-ffi.dll"
  )

# Import target "Realm::RealmFFIStatic" for configuration "Release"
set_property(TARGET Realm::RealmFFIStatic APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(Realm::RealmFFIStatic PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "C:/workspace/osp-gojimmypi/realm/VS2022/src/realm/object-store/c_api/Release/realm-ffi-static.lib"
  )

# Import target "Realm::Sync" for configuration "Release"
set_property(TARGET Realm::Sync APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(Realm::Sync PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "C:/workspace/osp-gojimmypi/realm/VS2022/src/realm/sync/Release/realm-sync.lib"
  )

# Import target "Realm::Storage" for configuration "MinSizeRel"
set_property(TARGET Realm::Storage APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(Realm::Storage PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_MINSIZEREL "C;CXX"
  IMPORTED_LOCATION_MINSIZEREL "C:/workspace/osp-gojimmypi/realm/VS2022/src/realm/MinSizeRel/realm.lib"
  )

# Import target "Realm::QueryParser" for configuration "MinSizeRel"
set_property(TARGET Realm::QueryParser APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(Realm::QueryParser PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_MINSIZEREL "CXX"
  IMPORTED_LOCATION_MINSIZEREL "C:/workspace/osp-gojimmypi/realm/VS2022/src/realm/parser/MinSizeRel/realm-parser.lib"
  )

# Import target "Realm::ObjectStore" for configuration "MinSizeRel"
set_property(TARGET Realm::ObjectStore APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(Realm::ObjectStore PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_MINSIZEREL "CXX"
  IMPORTED_LOCATION_MINSIZEREL "C:/workspace/osp-gojimmypi/realm/VS2022/src/realm/object-store/MinSizeRel/realm-object-store.lib"
  )

# Import target "Realm::RealmFFI" for configuration "MinSizeRel"
set_property(TARGET Realm::RealmFFI APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(Realm::RealmFFI PROPERTIES
  IMPORTED_IMPLIB_MINSIZEREL "C:/workspace/osp-gojimmypi/realm/VS2022/src/realm/object-store/c_api/MinSizeRel/realm-ffi.lib"
  IMPORTED_LOCATION_MINSIZEREL "C:/workspace/osp-gojimmypi/realm/VS2022/src/realm/object-store/c_api/MinSizeRel/realm-ffi.dll"
  )

# Import target "Realm::RealmFFIStatic" for configuration "MinSizeRel"
set_property(TARGET Realm::RealmFFIStatic APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(Realm::RealmFFIStatic PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_MINSIZEREL "CXX"
  IMPORTED_LOCATION_MINSIZEREL "C:/workspace/osp-gojimmypi/realm/VS2022/src/realm/object-store/c_api/MinSizeRel/realm-ffi-static.lib"
  )

# Import target "Realm::Sync" for configuration "MinSizeRel"
set_property(TARGET Realm::Sync APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(Realm::Sync PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_MINSIZEREL "CXX"
  IMPORTED_LOCATION_MINSIZEREL "C:/workspace/osp-gojimmypi/realm/VS2022/src/realm/sync/MinSizeRel/realm-sync.lib"
  )

# Import target "Realm::Storage" for configuration "RelWithDebInfo"
set_property(TARGET Realm::Storage APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(Realm::Storage PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "C;CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/workspace/osp-gojimmypi/realm/VS2022/src/realm/RelWithDebInfo/realm.lib"
  )

# Import target "Realm::QueryParser" for configuration "RelWithDebInfo"
set_property(TARGET Realm::QueryParser APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(Realm::QueryParser PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/workspace/osp-gojimmypi/realm/VS2022/src/realm/parser/RelWithDebInfo/realm-parser.lib"
  )

# Import target "Realm::ObjectStore" for configuration "RelWithDebInfo"
set_property(TARGET Realm::ObjectStore APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(Realm::ObjectStore PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/workspace/osp-gojimmypi/realm/VS2022/src/realm/object-store/RelWithDebInfo/realm-object-store.lib"
  )

# Import target "Realm::RealmFFI" for configuration "RelWithDebInfo"
set_property(TARGET Realm::RealmFFI APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(Realm::RealmFFI PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "C:/workspace/osp-gojimmypi/realm/VS2022/src/realm/object-store/c_api/RelWithDebInfo/realm-ffi.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/workspace/osp-gojimmypi/realm/VS2022/src/realm/object-store/c_api/RelWithDebInfo/realm-ffi.dll"
  )

# Import target "Realm::RealmFFIStatic" for configuration "RelWithDebInfo"
set_property(TARGET Realm::RealmFFIStatic APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(Realm::RealmFFIStatic PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/workspace/osp-gojimmypi/realm/VS2022/src/realm/object-store/c_api/RelWithDebInfo/realm-ffi-static.lib"
  )

# Import target "Realm::Sync" for configuration "RelWithDebInfo"
set_property(TARGET Realm::Sync APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(Realm::Sync PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/workspace/osp-gojimmypi/realm/VS2022/src/realm/sync/RelWithDebInfo/realm-sync.lib"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
