# CMake generated Testfile for 
# Source directory: C:/workspace/osp-gojimmypi/realm/realm-core-gojimmypi/test
# Build directory: C:/workspace/osp-gojimmypi/realm/VS2022/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(CoreTests "C:/workspace/osp-gojimmypi/realm/VS2022/test/Debug/realm-tests.exe")
  set_tests_properties(CoreTests PROPERTIES  _BACKTRACE_TRIPLES "C:/workspace/osp-gojimmypi/realm/realm-core-gojimmypi/tools/cmake/Utilities.cmake;54;add_test;C:/workspace/osp-gojimmypi/realm/realm-core-gojimmypi/test/CMakeLists.txt;211;add_bundled_test;C:/workspace/osp-gojimmypi/realm/realm-core-gojimmypi/test/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(CoreTests "C:/workspace/osp-gojimmypi/realm/VS2022/test/Release/realm-tests.exe")
  set_tests_properties(CoreTests PROPERTIES  _BACKTRACE_TRIPLES "C:/workspace/osp-gojimmypi/realm/realm-core-gojimmypi/tools/cmake/Utilities.cmake;54;add_test;C:/workspace/osp-gojimmypi/realm/realm-core-gojimmypi/test/CMakeLists.txt;211;add_bundled_test;C:/workspace/osp-gojimmypi/realm/realm-core-gojimmypi/test/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(CoreTests "C:/workspace/osp-gojimmypi/realm/VS2022/test/MinSizeRel/realm-tests.exe")
  set_tests_properties(CoreTests PROPERTIES  _BACKTRACE_TRIPLES "C:/workspace/osp-gojimmypi/realm/realm-core-gojimmypi/tools/cmake/Utilities.cmake;54;add_test;C:/workspace/osp-gojimmypi/realm/realm-core-gojimmypi/test/CMakeLists.txt;211;add_bundled_test;C:/workspace/osp-gojimmypi/realm/realm-core-gojimmypi/test/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(CoreTests "C:/workspace/osp-gojimmypi/realm/VS2022/test/RelWithDebInfo/realm-tests.exe")
  set_tests_properties(CoreTests PROPERTIES  _BACKTRACE_TRIPLES "C:/workspace/osp-gojimmypi/realm/realm-core-gojimmypi/tools/cmake/Utilities.cmake;54;add_test;C:/workspace/osp-gojimmypi/realm/realm-core-gojimmypi/test/CMakeLists.txt;211;add_bundled_test;C:/workspace/osp-gojimmypi/realm/realm-core-gojimmypi/test/CMakeLists.txt;0;")
else()
  add_test(CoreTests NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(SyncTests "C:/workspace/osp-gojimmypi/realm/VS2022/test/Debug/realm-sync-tests.exe")
  set_tests_properties(SyncTests PROPERTIES  _BACKTRACE_TRIPLES "C:/workspace/osp-gojimmypi/realm/realm-core-gojimmypi/tools/cmake/Utilities.cmake;54;add_test;C:/workspace/osp-gojimmypi/realm/realm-core-gojimmypi/test/CMakeLists.txt;275;add_bundled_test;C:/workspace/osp-gojimmypi/realm/realm-core-gojimmypi/test/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(SyncTests "C:/workspace/osp-gojimmypi/realm/VS2022/test/Release/realm-sync-tests.exe")
  set_tests_properties(SyncTests PROPERTIES  _BACKTRACE_TRIPLES "C:/workspace/osp-gojimmypi/realm/realm-core-gojimmypi/tools/cmake/Utilities.cmake;54;add_test;C:/workspace/osp-gojimmypi/realm/realm-core-gojimmypi/test/CMakeLists.txt;275;add_bundled_test;C:/workspace/osp-gojimmypi/realm/realm-core-gojimmypi/test/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(SyncTests "C:/workspace/osp-gojimmypi/realm/VS2022/test/MinSizeRel/realm-sync-tests.exe")
  set_tests_properties(SyncTests PROPERTIES  _BACKTRACE_TRIPLES "C:/workspace/osp-gojimmypi/realm/realm-core-gojimmypi/tools/cmake/Utilities.cmake;54;add_test;C:/workspace/osp-gojimmypi/realm/realm-core-gojimmypi/test/CMakeLists.txt;275;add_bundled_test;C:/workspace/osp-gojimmypi/realm/realm-core-gojimmypi/test/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(SyncTests "C:/workspace/osp-gojimmypi/realm/VS2022/test/RelWithDebInfo/realm-sync-tests.exe")
  set_tests_properties(SyncTests PROPERTIES  _BACKTRACE_TRIPLES "C:/workspace/osp-gojimmypi/realm/realm-core-gojimmypi/tools/cmake/Utilities.cmake;54;add_test;C:/workspace/osp-gojimmypi/realm/realm-core-gojimmypi/test/CMakeLists.txt;275;add_bundled_test;C:/workspace/osp-gojimmypi/realm/realm-core-gojimmypi/test/CMakeLists.txt;0;")
else()
  add_test(SyncTests NOT_AVAILABLE)
endif()
subdirs("util")
subdirs("object-store")
subdirs("benchmark-common-tasks")
subdirs("benchmark-crud")
subdirs("benchmark-larger")
subdirs("benchmark-sync")
